# Generated by Django 6.0.1 on 2026-01-31 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_title_3e32b6_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry-Level'), ('mid', 'Mid-Level'), ('senior', 'Senior')], db_index=True, default='entry', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'location', 'job_type', 'experience_level'], name='jobs_job_title_f68e15_idx'),
        ),
    ]
